#!/bin/sh
# Give dmenu list of all unicode characters to copy.
# Shows the selected character in notifications if running.

# Must have wl-copy installed to even show menu.
wl-copy -h &>/dev/null || exit

chosen=$(grep -v "#" $HOME/.scripts/bemenu/emoji | bemenu -i -l 20 --fn Noto-18)

[ "$chosen" != "" ] || exit

c=$(echo "$chosen" | sed "s/ .*//")
#echo "$c" | tr -d '\n' | xclip -selection clipboard
echo "$c" | tr -d '\n' | wl-copy
notify-send "'$c' copied to clipboard." &

#s=$(echo "$chosen" | sed "s/.*; //" | awk '{print $1}')
#echo "$s" | tr -d '\n' | xclip
#notify-send "'$s' copied to primary." &
