#!/bin/sh
#   ________
#  /_  __/ /_  __  _________  ______ ___
#   / / / __ \/ / / / ___/ / / / __ `__ \
#  / / / / / / /_/ / /  / /_/ / / / / / /
# /_/ /_/ /_/\__, /_/   \__,_/_/ /_/ /_/
#           /____/
#
# Filename:   .config/aliasrc
# Github:     https://github.com/Thyrum/dotfiles
# Maintainer: Thyrum (Aron de Jong)

# Trash commands
command -v rmtrash    >/dev/null && alias rm=rmtrash
command -v rmdirtrash >/dev/null && alias rmdir=rmdirtrash
# This one is to make sudo use trash as well
alias sudo="sudo "

# Uni commands
alias sshUni="TERM=screen-256color ssh -t -A -X s2120437@sshgw.leidenuniv.nl ssh -X huisuil01"
alias sshfsUni="sshfs s2120437@sshgw.leidenuniv.nl:/vol/home/s2120437 /mnt/aron/uni -o transform_symlinks"
alias wgetUni="wget --user=s2120437 --ask-password"

# General settings
alias vim="nvim"
alias sp="sudo pacman"
alias cp="cp -i"      # Confirm overwriting
alias df="df -h"      # Human readable sizes
alias free="free -m"  # show sizes in MB
alias more=less
alias gs="git status"
alias g="git"
alias make="make -j"  # always run make multithreaded

# Enable color by default
alias ls="ls --color=auto"
alias grep="grep --color=auto"
alias egrep="egrep --color=auto"
alias fgrep="fgrep --color=auto"

# tmux shortcuts
alias t="tmux"
alias ta="tmux attach -t"
alias tls="tmux ls"
alias tn="tmux new -s"


# Fun
alias starwars="telnet towel.blinkenlights.nl"
alias getlinks='ls -A | xargs stat --printf="%n\t%h\n" | sed -e "/\t1$/d" | column --table'

alias RoboCom="wine '$HOME/.wine/drive_c/Program Files (x86)/RoboCom Workshop/RoboCom.exe'"
