#!/bin/sh

if bluetoothctl show | grep -e "Powered: yes" >/dev/null; then
	status="off"
else
	status="on"
fi

if [[ "${BLOCK_BUTTON}" == "1" ]]; then
	if [[ "$status" == "on" ]]; then
		swaymsg exec blueman-manager
	fi
fi

echo -e "$status\n$status"
echo "#0000FF"
