#!/bin/sh

if bluetoothctl show | grep -e "Powered: yes" >/dev/null; then
	status="on"
else
	status="off"
fi

if [ "${BLOCK_BUTTON}" = "1" ]; then
	if [ "$status" = "on" ]; then
		swaymsg exec blueman-manager
	fi
fi

echo "$status\n$status"
echo "#0000FF"
