#!/bin/sh

[ -z "${BLOCK_BUTTON}" ] || pamixer --toggle-mute

volume=$(pamixer --get-volume)
mute=$(pamixer --get-mute)

if [ "$mute" = "true" ]; then
	icon=🔇
elif [ "$volume" -gt "75" ]; then
	icon=🔊
elif [ "$volume" -gt "25" ]; then
	icon=🔉
else
	icon=🔈
fi

# Full and short text respectively
echo "$icon $volume%"
echo "$volume%"

# Color
if [ "$mute" = "false" ]; then
	echo "#00FF00"
else
	echo "#FF0000"
fi
