#!/bin/sh

if swaymsg -t get_inputs | jq '.[0].xkb_active_layout_name' | grep -e "euro" >/dev/null
then
	notify-send "Switched to DVORAK"
	swaymsg input "*" xkb_layout "us"
	swaymsg input "*" xkb_variant "dvorak"
else
	notify-send "Switched to QWERTY"
	swaymsg input "*" xkb_layout "us"
	swaymsg input "*" xkb_variant "euro"
fi
