#! /bin/sh
#   ________
#  /_  __/ /_  __  _________  ______ ___
#   / / / __ \/ / / / ___/ / / / __ `__ \
#  / / / / / / /_/ / /  / /_/ / / / / / /
# /_/ /_/ /_/\__, /_/   \__,_/_/ /_/ /_/
#           /____/
#
# Filename:   .config/bspwm/bspwmrc
# Github:     https://github.com/Thyrum/dotfiles
# Maintainer: Thyrum (Aron de Jong)


#### AUTOSTART ####

sxhkd &
picom &

bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc config external_rules_command $DOTFILES/.config/bspwm/external_rules

#### MONITOR SETUP ####
i=1
for monitor in $(bspc query -M); do
	bspc monitor $monitor \
		-n "$i" \
		-d I II III IV V VI VII VIII IX X
	let i++
done
unset i

### AUTO LOCK ###
# after 300 seconds, dim the screen, 5 second later lock
xset s 300 5
xss-lock -n /usr/lib/xsecurelock/dimmer -l -- env XSECURELOCK_AUTH_TIMEOUT=5 xsecurelock &

$HOME/.config/polybar/launch.sh
feh --randomize --bg-fill $DOTFILES/wallpaper/*
