#!/bin/sh
[ -z "$1" ] && exit # If $1 is left, hovers in the bottom left, if right, the bottom right

swaymsg resize set 33 ppt 33 ppt

focused_screen=`swaymsg -t get_outputs | jq '.[] | select(.focused==true) | .rect'`
screenwidth=`echo "$focused_screen" | jq '.width + .x'`
screenheight=`echo "$focused_screen" | jq '.height + .y'`

focused_window=`swaymsg -t get_tree | jq '.. | (.["nodes","floating_nodes"]? // empty) [] | select(.focused==true) | .rect'`
newwidth=`echo $focused_window | jq '.width'`
newheight=`echo $focused_window | jq '.height'`

vertical=$(expr $screenheight - $newheight)

case "$1" in
	left)  horizontal=`echo "$focused_screen" | jq '.x'`;;
	right) horizontal=`expr $screenwidth - $newwidth`;;
esac

echo "height: $newheight"
echo "width: $newwidth"
echo "screenwidth: $screenwidth"
echo "screenheight: $screenheight"

swaymsg move absolute position $horizontal $vertical

echo "new horizontal: $horizontal"
echo "new vertical: $vertical"
