#!/bin/sh

# Toggle floating dropdown terminal in i3, or start if non-existing.
# $1 is	the script run in the terminal.
# All other args are terminal settings.
# Terminal names are in dropdown_* to allow easily setting i3 settings.

[ -z "$1" ] && exit

if swaymsg -t get_tree | grep "\"dropdown_$1\"," >/dev/null;
then
	echo "Window detected"
	visible=$(swaymsg -t get_tree | jq ".. | (.[\"nodes\",\"floating_nodes\"]? // empty) [] | select(.name==\"dropdown_$1\") | .visible")
	if $visible; then
		echo "$visible Hiding"
		swaymsg "[title=\"dropdown_$1\"] move to scratchpad";
	else
		echo "Showing"
		swaymsg "[title=\"dropdown_$1\"] scratchpad show; [title=\"dropdown_$1\"] move position center";
	fi
else
	echo "Window not detected, now spawning."
	swaymsg "exec --no-startup-id $TERMINAL --title=dropdown_$1 -e $1"
fi
