#!/bin/bash

bashscripts="${DOTFILES}/scripts/.scripts/tmux"

show_help() {
	echo 'Usage: muxify [[music],[uni],[pid]] [arguments]';
}

key="$1"
shift
case $key in
	"music"|"Music")
		source ${bashscripts}/tmuxMusic.sh $@
		;;
	"uni"|"Uni")
		if ! source ${bashscripts}/tmuxUni.sh $@ ; then
			show_help
			exit 1
		fi
		;;
	"pid"|"Pid")
		source ${bashscripts}/tmuxPid.sh $@
		;;
	*)
		show_help
		;;
esac

exit 0
